language: ruby
rvm:
- 2.3.3
addons:
  ssh_known_hosts: cloud.elfgzp.cn
before_install:
- openssl aes-256-cbc -K $encrypted_f91baf41390f_key -iv $encrypted_f91baf41390f_iv
  -in id_ras_deploy.enc -out ~/.ssh/id_ras_deploy -d
- chmod 600 ~/.ssh/id_ras_deploy
- cp ssh_config ~/.ssh/config
script:
- bundle install
- bundle exec jekyll build
after_success:
- ssh gzp@cloud.elfgzp.cn "cd ~/workspace/elfgzp.github.io && source ~/.zshrc  && git pull origin master
  && docker-compose build && docker-compose down && docker-compose up -d"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
